### PR TITLE
Replace calls to `__builtin_nanX` with expression leading to NaN

### LINKED ISSUE #78: `__builtin_nanf("")` in global initializers
`FFmpeg` conatains globals that are initialized to NaN via `__builtin_nanf("")` .

~~~C
double d = __builtin_nanf("");

int main(void) {
	return 0;
}
~~~

```
1.c:1: Error: global initializer
```

### PR DESCRIPTION
**Pull request by michael-schwarz**
Fixes https://github.com/goblint/cil/issues/78, by replacing calls to `__builtin_nanX` which may not appear in locations where we expect a constant value, e.g. global initializers, with the expression `0./0.` which will yield NaN (on any sensible machine).

Needed for https://github.com/goblint/bench/issues/14

### CODE REVIEW

File: src/frontc/cabs2cil.ml [hunk 1]
```diff
@@ -4269,76 +4263,75 @@ and doExp (asconst: bool)   (* This expression is used as a constant *)
...
+          | Lval (Var fv, NoOffset) -> fv.vname = "__builtin_nan" || fv.vname = "__builtin_nanf" ||
+            fv.vname = "__builtin_nanl" || fv.vname = "__builtin_nans" || fv.vname = "__builtin_nansf" || fv.vname = "__builtin_nansl"
+          | _ -> false
+        in
+        if isBuiltinNan && asconst then
+          (* Replace call to builtin nan with computation yielding NaN *)
+          let onef = Const(CReal(0.0,FDouble,None)) in
+          let zerodivzero = mkCast (BinOp(Div,onef,onef,doubleType)) resType in
+          (empty,zerodivzero,resType)
+        else (
```
Comment (michael-schwarz) [inline src/frontc/cabs2cil.ml]: This is the only semantic diff, the rest is just due to the crazy indenting CIL had that I needed to fix to wrap my head around things.

File: src/frontc/cabs2cil.ml [hunk 2]
```diff
@@ -4269,76 +4263,75 @@ and doExp (asconst: bool)   (* This expression is used as a constant *)
               fv.vname = "__builtin_choose_expr" || fv.vname = "__builtin_tgmath"
             | _ -> false
         in
-
+        let isBuiltinNan =
+          match f'' with
+          | Lval (Var fv, NoOffset) -> fv.vname = "__builtin_nan" || fv.vname = "__builtin_nanf" ||
+            fv.vname = "__builtin_nanl" || fv.vname = "__builtin_nans" || fv.vname = "__builtin_nansf" || fv.vname = "__builtin_nansl"
```
Comment (sim642) [inline src/frontc/cabs2cil.ml]: I think this could be pattern matched even more, like
```ocaml
Lval (Var {vname=("__builtin_nan" | "__builtin_nanf" | ...); _}, NoOffset
```

File: src/frontc/cabs2cil.ml [hunk 3]
```diff
@@ -4269,76 +4263,75 @@ and doExp (asconst: bool)   (* This expression is used as a constant *)
...
+          | _ -> false
+        in
+        if isBuiltinNan && asconst then
+          (* Replace call to builtin nan with computation yielding NaN *)
+          let onef = Const(CReal(0.0,FDouble,None)) in
+          let zerodivzero = mkCast (BinOp(Div,onef,onef,doubleType)) resType in
```
Comment (sim642) [inline src/frontc/cabs2cil.ml:4267]: Shouldn't `FDouble` and `doubleType` depend on the suffix of the function to be of the correct type?

Comment (michael-schwarz) [reply src/frontc/cabs2cil.ml:4267]: Yes, one could do that. Instead I always use double here and then convert to the correct type with a cast in `mkCast`. This cast should preserve the NaN-ness of the value.

Comment (sim642) [reply src/frontc/cabs2cil.ml:4267]: Ah, right, the `__builtin_nan*` functions are declared as builtins already with corresponding return types. I didn't realize those were already specified somewhere.

**Review by sim642 — APPROVED** [review]
